### ISSUE TITLE
Link for Data Not Working

### ISSUE THREAD

**Issue by mosaddek-hossain** [naity/citeseq_autoencoder#1]
Hi,
Please check the link for data. It is not working.

**Comment by naity** [comment]
The link has been fixed. Thank you!

**Comment by mosaddek-hossain** [comment]
Hello Sir,
I have just checked the link. Still it is not working. I am getting this error. 404 That file isn’t here any more.
![Screenshot from 2020-02-10 09-43-41](https://user-images.githubusercontent.com/48623052/74120614-f817e480-4be9-11ea-92b6-20ea7a170f5d.png)

**Comment by naity** [comment]
The new link works for me. Please go to the post and try again. Thank you.
