### ISSUE TITLE
Link for Data Still Not Working

### ISSUE THREAD

**Issue by mosaddek-hossain** [naity/citeseq_autoencoder#2]
Hello Sir,
I have just checked the link for Data once again. Still it is not working. I am getting error: 404
That file isn’t here any more. Please check it.

![Screenshot from 2020-02-10 09-43-41](https://user-images.githubusercontent.com/48623052/74120691-58a72180-4bea-11ea-8b80-9e83faaa8cbc.png)

**Comment by cbjackson42** [comment]
I also am having this issue

**Comment by naity** [comment]
The link has been fixed.
